// <auto-generated />
using CodeCafe.Modules.Platform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeCafe.Modules.Platform.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PlatformDbContext))]
[Migration("20260605085903_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

        modelBuilder.Entity("CodeCafe.Modules.Platform.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("TEXT")
                    .HasColumnName("Id");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("CreatedAtUtc");

                b.Property<string>("DisplayName")
                    .HasMaxLength(120)
                    .HasColumnType("TEXT")
                    .HasColumnName("DisplayName");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("TEXT")
                    .HasColumnName("Email");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("PasswordHash");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users", (string)null);
            });
#pragma warning restore 612, 618
    }
}
